327 typeerror schedule jobs missing 1 required positional argument week info great football pool tgfp web (#330)
* Change the job scheduler to replace the old schedule

Old jobs were stuck in the scheduler that had the wrong parameters, this will flush out / replace the jobs

* Updated version